### ISSUE TITLE
Nothing happen while executing !rbp stationID

### ISSUE THREAD

**Issue by riauas** [azlux/botamusique#138] opened 2020-04-30 02:03 UTC
It always happen after querying radio streaming and want to playing particular radio by using cmd !rbp stationID. Currently using botamusique ver 6.2 latest release 5fbc8e4

The log says about it:
[Apr 25 18:18:25 INFO Thread-2] bot: rbp matches rbplay
[Apr 25 18:18:25 ERROR Thread-2] bot: command rbplay failed with error: Traceback (most recent call last):
  File "mumbleBot.py", line 298, in message_received
    self.cmd_handle[command_exc]['handle'](self, user, text, command_exc, parameter)
  File "/home/XxX/Downloads/botamusique/command.py", line 475, in cmd_rb_play
    url = radiobrowser.geturl_byid(parameter)
  File "/home/XxX/Downloads/botamusique/librb/radiobrowser.py", line 19, in geturl_byid
    url = rb.playable_station(id)['url']
KeyError: 'url'

**Comment by TerryGeng** [comment] 2020-04-30 04:46
This is probably caused by we using a deprecated library of radiobrowser.info.

It seems that newer version of the python library https://pypi.org/project/pyradios/ is available. I'm wondering that whether @elpatron68, the original maintainer of the radiobrowser part, is willing to help us update the library :).

**Comment by elpatron68** [comment] 2020-04-30 06:43
Hi @TerryGeng , I will try to find some time next week to have a look at the problem.

**Comment by azlux** [comment] 2020-04-30 08:11
Hi, 
Terry is right, we use an old function. This the main project have now a pypi version, we can switch to an up-to-date version.
But radiobrowser havn't force the new API, this command should work. Did you try another station ID for testing ?

**Comment by riauas** [comment] 2020-04-30 15:50
Hi @azlux , yes i did. 
I tried several radios, some of it run normal but another radio i tried ended with KeyError: 'url'

**Comment by elpatron68** [comment] 2020-04-30 19:10
I just tested rb with 3 of my favorite stations, no problems. The URLs from http://www.radio-browser.info/ are checked in regular intervals and are beeing marked as broken in the database if they don´t work. I don´t remember if my API calls check for the broken flag, will have a look at the code the next days.

**Comment by TerryGeng** [comment] 2020-05-01 00:53
@riauas I think it would also be helpful if you provide the radio ID you used to reproduce this bug.

**Comment by riauas** [comment] 2020-05-02 01:04
Hi @TerryGeng sorry for slow response, here are shortlist of the radio ID i've used to reproduce the bug: 120925, 120926, 120927, 96311, 101975

**Comment by felix91gr** [comment] 2020-05-07 02:34
> This is probably caused by we using a deprecated library of radiobrowser.info.
> 
> It seems that newer version of the python library https://pypi.org/project/pyradios/ is available. I'm wondering that whether @elpatron68, the original maintainer of the radiobrowser part, is willing to help us update the library :).

Oh, it's great that you're already working on this. I just came in to say that http://www.radio-browser.info/webservice/ was deprecated, but you guys already know :3

**Comment by TerryGeng** [comment] 2020-05-30 12:57
Hi, I'm wondering is there any progress about this issue?

**Closed** 2020-06-01 13:34 UTC
Labels: bug, priority/P2 - Important
