### ISSUE TITLE
Error on servers with welcome text (?)

### ISSUE THREAD

**Issue by Natenom** [azlux/botamusique#281] opened 2021-05-24 20:53 UTC
**Describe the bug**
Error in log when server sends a welcome message.

[May 24 22:47:44 INFO] bot: botamusique version 7.2, starting...
[May 24 22:47:44 INFO] Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/botam/botamusique/mumbleBot.py", line 243, in message_received
    user = self.mumble.users[text.actor]['name']
KeyError: 0

**Affected version**
Latest release from azlux.fr

**To Reproduce**
1. Let a bot connect to any server with a welcome message
2. See error

**Expected behavior**
No log entry.

**Comment by azlux** [comment] 2021-05-24 21:55
Hi,
I have also a welcome message, and welcome isn't a textmessage, it's a ServerSync protobuff information.
And with ServerSync, welcome_text should never reach `message_received` function.
Do you use any plugins or ICE script to send the welcome message instead of the builtin function ?
If yes, the issue is you don't send any username when you send the welcome message.

**Comment by Natenom** [comment] 2021-05-26 01:19
I disabled all MumbleModerator Modules (Ice) on my server and the message is still there.

**Comment by TerryGeng** [comment] 2021-05-26 01:27
Sorry for accidentally closing this issue.

I have just pushed a fix to the master branch. Would you like to confirm it works or not?

To install, you need to install the _Nightly build_ (see the README) or pull the master branch directly.

**Comment by Natenom** [comment] 2021-05-26 01:35
Jupp, is fixed, thank you :)

**Comment by TerryGeng** [comment] 2021-05-26 01:36
Great to know it :)

**Closed** 2021-05-26 01:36 UTC

**Comment by azlux** [comment] 2021-05-26 07:25
Thanks for the fix terry. But I still curious how a welcome message can raise this issue. This is not part from the mumble protocol. What's your murmur version ?

**Comment by TerryGeng** [comment] 2021-05-26 07:34
Sometimes Murmur would send a "Server" Message, which doesn't have a valid `actor`.

On Mumble's side, when TextMessage is received,
https://github.com/mumble-voip/mumble/blob/05db5fe6fc50df028ecfbd65ac274c7f33908cf2/src/mumble/Messages.cpp#L1025-L1035

Where the ACTOR_INIT is a macro that determines the actor, defined at 
https://github.com/mumble-voip/mumble/blob/05db5fe6fc50df028ecfbd65ac274c7f33908cf2/src/mumble/Messages.cpp#L42-L46

It is shown that if the message doesn't have a valid `actor`, it would be treated as the server's message (L1034).
