### ISSUE TITLE
Error playing some musiс from youtube

### ISSUE THREAD

**Issue by LDelOff** [azlux/botamusique#83] opened 2020-02-29 08:29 UTC
**I enter:**
 ! url https://www.youtube.com/watch?v=eNTjM3_0N80
**I get:**
**mumble:**
url: Command failed with error: TypeError: 'bool' object is not subscriptable.
**console:**
[Feb 29 08:14:49 INFO Thread-2] bot: received command url - <a href="https://www.youtube.com/watch?v=eNTjM3_0N80"> https://www.youtube.com / watch? v = eNTjM3_0N80 </a> by L_DelOff
[]
[youtube] eNTjM3_0N80: Downloading webpage
[youtube] eNTjM3_0N80: Downloading video info webpage
[youtube] Downloading just video eNTjM3_0N80 because of --no-playlist
[youtube] eNTjM3_0N80: Downloading js player vflsFV4r3
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/extractor/youtube.py", line 1380, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/extractor/youtube.py", line 1293, in _extract_signature_function
    cache_res = res (test_string)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/extractor/youtube.py", line 1356, in <lambda>
    return lambda s: initial_function ([s])
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/jsinterp.py", line 258, in resf
    res, abort = self.interpret_statement (stmt, local_vars)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression (expr, local_vars, allow_recursion)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/jsinterp.py", line 92, in interpret_expression
    m.group ('expr'), local_vars, allow_recursion - 1)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/jsinterp.py", line 189, in interpret_expression
    m.group ('x'), local_vars, allow_recursion - 1)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression (expr, local_vars, allow_recursion)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/jsinterp.py", line 211, in interpret_expression
    raise ExtractorError ('Unsupported JS expression% r'% expr)
youtube_dl.utils.ExtractorError: Unsupported JS expression '[341717124,572208085,'; please report this issue on https://yt-dl.org/bug. Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError ("Unsupported JS expression '[341717124,572208085,'; please report this issue on https://yt-dl.org/bug. Make sure you are using the latest version; see https: // yt- dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. ")); please report this issue on https://yt-dl.org/bug. Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

client: mumble 1.3.0(win 10)
server: orange pi 3. Armbian bullseye with Linux 5.5.0-sunxi64
[configuration.txt](https://github.com/azlux/botamusique/files/4270069/configuration.txt)

**Comment by LDelOff** [comment] 2020-02-29 08:30
But  !url https://www.youtube.com/watch?v=O6YzU00oack works correctly

**Comment by TerryGeng** [comment] 2020-02-29 09:15
According to the log you have posted is related to youtube-dl. I would suggest you update your youtube-dl to the newest version.

If the problem persists, please try run youtube-dl along,
```
youtube-dl https://www.youtube.com/watch?v=eNTjM3_0N80
```

If something went wrong again, I think you'd better report this error to youtube-dl.

**Comment by LDelOff** [comment] 2020-02-29 09:37
Thank you! 
Sorry, I think, that youtube-dl update with botamusique.

**Comment by azlux** [comment] 2020-02-29 10:03
@LDelOff you can use the command `!update` with the bot, it will update youtube-dl with `pip`

**Comment by LDelOff** [comment] 2020-02-29 10:19
[Feb 29 10:17:33 INFO Thread-8] bot: received command update -  by L_DelOff
[Feb 29 10:17:33 ERROR Thread-8] bot: command update failed with error: Traceback (most recent call last):
  File "mumbleBot.py", line 276, in message_received
    self.cmd_handle[command](self, user, text, command, parameter)
  File "/root/botamusique/command.py", line 481, in cmd_update
    constants.strings('start_updating'))
  File "/root/botamusique/pymumble/pymumble_py3/users.py", line 238, in send_text_message
    raise TextTooLongError(self.mumble_object.get_max_message_length())
pymumble.pymumble_py3.errors.TextTooLongError: Maximum Text allowed length: 0

**Comment by azlux** [comment] 2020-02-29 10:21
@LDelOff are you able to receive message when you do `!help` ?
Look like the server don't send well the maximum text length variable.

**Comment by LDelOff** [comment] 2020-02-29 10:31
[13:31:15] (Канал) ВеликийГусляр:  Commands Control  !play (or !p) [{num}] - resume from pausing / start to play (the num-th song is num is given)  !pause - pause  !stop - stop playing  !skip - jump to the next song  !volume {volume} - get or change the volume (from 0 to 100)  !mode [{mode}] - get or set the playback mode, {mode} should be one of one-shot (remove item once played), repeat (looping through the playlist), random (randomize the playlist) !duck on/off - enable or disable ducking function  !duckv - set the volume of the bot when ducking is activated  !duckthres - set the threshold of volume to activate ducking (3000 by default)  Playlist  !now (or !np) - display the current song  !queue - display items in the playlist  !file (or !f) {path/folder/index/keyword} - append file to the playlist by its path or index returned by !listfile  !filematch (or !fm) {pattern} - add all files that match regex {pattern}  !url {url} - append youtube or soundcloud music to the playlist  !playlist {url} [{offset}] - append items in a youtube or soundcloud playlist, and start with the {offset}-th item  !rm {num} - remove the num-th song on the playlist  !repeat [{num}] - repeat current song {num} (1 by default) times. !random - randomize the playlist. !radio {url} - append a radio {url} to the playlist  !rbquery {keyword} - query http://www.radio-browser.info for a radio station  !rbplay {id} - play a radio station with {id} (eg. !rbplay 96746)  !listfile [{pattern}] - display list of available files (that match the regex pattern if {pattern} is given)  !oust - stop playing and go to default channel  Other  !joinme {token} - join your own channel with {token}.
--

**Comment by azlux** [comment] 2020-02-29 10:43
Can you send us the [strings] part of you custom `configuration.init` ?

**Comment by LDelOff** [comment] 2020-02-29 11:19
[configuration.example.txt](https://github.com/azlux/botamusique/files/4270209/configuration.example.txt)
[configuration.txt](https://github.com/azlux/botamusique/files/4270210/configuration.txt)
[configuration.default.txt](https://github.com/azlux/botamusique/files/4270211/configuration.default.txt)

**Comment by TerryGeng** [comment] 2020-02-29 11:24
It is likely that this is caused by the murmur server-side. But the help command can be sent correctly, looks weird.

I suggest you restart the murmur server, or restart the bot. And try update again.

**Comment by LDelOff** [comment] 2020-02-29 11:35
I reboot server, with orange pi. Did not work(

**Comment by azlux** [comment] 2020-02-29 12:30
If you know python a little bit, you can add before this line https://github.com/azlux/pymumble/blob/c728985baf0a9dae731412b7dee1e434f8740213/pymumble_py3/users.py#L233
the file is `/root/botamusique/pymumble/pymumble_py3/users.py`

```
print("## Additionnal debug info")
print(len(message))
print(message)
print(self.mumble_object.get_max_image_length())
print(self.mumble_object.get_max_message_length())
```

You will have more output when running the bot.

**Comment by TerryGeng** [comment] 2020-02-29 13:23
Ummm... On my side nothing went wrong
![image](https://user-images.githubusercontent.com/2306637/75608305-5bd26500-5b39-11ea-980c-c038b4521d30.png)

I suspect that this is the problem of the murmur server. If you want to dig out more please follow azlux's instruction that put these line into your bot so we can see more debug info.

**Comment by LDelOff** [comment] 2020-02-29 14:19
I  follow azlux's instruction. Result:
![image](https://user-images.githubusercontent.com/51275636/75609189-86132b00-5b17-11ea-87de-ca95b7a79796.png)

![image](https://user-images.githubusercontent.com/51275636/75609193-8ca1a280-5b17-11ea-972b-e69dd326e5c1.png)


![image](https://user-images.githubusercontent.com/51275636/75609208-9fb47280-5b17-11ea-84db-97620de13c03.png)

**Comment by TerryGeng** [comment] 2020-02-29 15:05
Teriffic... So both
```
print(self.mumble_object.get_max_image_length())
print(self.mumble_object.get_max_message_length())
```
gave us 0.

The situation is even stranger since all messages the bot sends would go through this length check, and you already tried `!help` and it worked well. Why this error only occurs on `!update`?

I hope you can help us test more commands, if other commands work well, then it may indicate something....

**Comment by Lartza** [comment] 2020-03-01 09:30
@azlux
https://github.com/azlux/pymumble/blob/32994d402c76ef9b20a19858a137e3bade0fc08d/pymumble_py3/channels.py#L174-L179

https://github.com/azlux/pymumble/blob/pymumble_py3/pymumble_py3/users.py#L233-L238

Afaict infinite message length has never worked for whispers for non-image messages

**Comment by azlux** [comment] 2020-03-02 13:40
can I close this issue ?

**Comment by LDelOff** [comment] 2020-03-02 14:03
I think its problem my server.
![image](https://user-images.githubusercontent.com/51275636/75683112-9ce88780-5ca7-11ea-89f3-0e0528d094c9.png)
If no one else had problems, then you can close

**Comment by Lartza** [comment] 2020-03-02 14:43
@LDelOff Did you update? It should be fixed in the latest version of pymumble

**Comment by LDelOff** [comment] 2020-03-02 15:32
I completely deleted the folder with botamusique and at 16:57 installed a new one with github

**Comment by azlux** [comment] 2020-03-02 15:40
@LDelOff My bad, pymumble submodule wasn't updated on botamusique. Can you re-test ?

**Comment by LDelOff** [comment] 2020-03-02 16:02
It working!!!)))
![image](https://user-images.githubusercontent.com/51275636/75693526-16887180-5cb8-11ea-8b78-3f37117aafdd.png)
Thank You!

**Closed** 2020-03-02 16:06 UTC
Labels: help wanted
