### ISSUE TITLE
Traceback IndexError list assignment index out of range

### ISSUE THREAD

**Issue by Qwerty-Space** [azlux/botamusique#89] opened 2020-03-03 00:06 UTC
![image](https://user-images.githubusercontent.com/6967592/75729449-c541a780-5ce2-11ea-981e-b4693a77291c.png)

video https://www.youtube.com/watch?v=r1Rv5TtpwRQ

**Comment by TerryGeng** [comment] 2020-03-03 01:35
Can you provide more description about how to reproduce this bug? I can't reproduce it.

**Comment by TerryGeng** [comment] 2020-03-03 02:22
I managed to locate a subtle bug. Please have a look

**Comment by TerryGeng** [comment] 2020-03-03 16:35
All related issues has been fixed in #90. Closing this issue.

**Closed by TerryGeng** 2020-03-03 16:35 UTC
Labels: bug
